version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-node-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8oc6uoetwakv"
s3_prefix = "sam-node-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
